import './globals.css'

import { LucideBrushCleaning } from 'lucide-react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import { ModeToggle } from '@/components/theme/mode-toggle'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { choresPath, homePath } from '@/paths'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="fixed top-0 right-0 left-0 z-20 flex w-full justify-between gap-x-2 border-b border-slate-500 p-6 font-bold">
            <Link
              href={homePath()}
              className={cn(
                buttonVariants({ variant: 'ghost' }),
                'text-xl font-bold',
              )}
            >
              <LucideBrushCleaning /> Home
            </Link>
            <div className="flex items-center gap-x-4">
              <ModeToggle />
              <Link
                href={choresPath()}
                className={buttonVariants({ variant: 'default' })}
              >
                Chores
              </Link>
            </div>
          </nav>
          <main className="flex min-h-screen flex-1 flex-col overflow-x-hidden overflow-y-auto px-8 py-32">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
