#!/bin/sh

echo "🔧 Fixing lint issues..."
npm run lint-fix || exit 1
echo "✅ Lint fixes applied"

echo "➡️ Running pre-push checks..."
echo "🔍 Linting..."
npm run lint || exit 1
echo "✅ Lint passed"

echo "🔍 Type checking..."
npm run type-check|| exit 1
echo "✅ Types validated"

